---

- hosts: all
  become: true
  tasks:

  - name: Update Repository Index (Ubuntu)
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: docker
  become: true
